package com.imooc.policy.dal;

import com.imooc.policy.model.BehaviorModel;

public interface BehaviorModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior
     *
     * @mbg.generated Tue Feb 14 10:38:00 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior
     *
     * @mbg.generated Tue Feb 14 10:38:00 CST 2023
     */
    int insert(BehaviorModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior
     *
     * @mbg.generated Tue Feb 14 10:38:00 CST 2023
     */
    int insertSelective(BehaviorModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior
     *
     * @mbg.generated Tue Feb 14 10:38:00 CST 2023
     */
    BehaviorModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior
     *
     * @mbg.generated Tue Feb 14 10:38:00 CST 2023
     */
    int updateByPrimaryKeySelective(BehaviorModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior
     *
     * @mbg.generated Tue Feb 14 10:38:00 CST 2023
     */
    int updateByPrimaryKey(BehaviorModel record);
}