package com.imooc.policy.dal;

import com.imooc.policy.model.ClickModel;

public interface ClickModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table click
     *
     * @mbg.generated Fri Feb 24 14:37:03 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table click
     *
     * @mbg.generated Fri Feb 24 14:37:03 CST 2023
     */
    int insert(ClickModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table click
     *
     * @mbg.generated Fri Feb 24 14:37:03 CST 2023
     */
    int insertSelective(ClickModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table click
     *
     * @mbg.generated Fri Feb 24 14:37:03 CST 2023
     */
    ClickModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table click
     *
     * @mbg.generated Fri Feb 24 14:37:03 CST 2023
     */
    int updateByPrimaryKeySelective(ClickModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table click
     *
     * @mbg.generated Fri Feb 24 14:37:03 CST 2023
     */
    int updateByPrimaryKey(ClickModel record);
}