package com.imooc.policy.dal;

import com.imooc.policy.model.FavoriteModel;

import java.util.List;

public interface FavoriteModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbg.generated Wed Feb 22 13:04:31 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbg.generated Wed Feb 22 13:04:31 CST 2023
     */
    int insert(FavoriteModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbg.generated Wed Feb 22 13:04:31 CST 2023
     */
    int insertSelective(FavoriteModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbg.generated Wed Feb 22 13:04:31 CST 2023
     */
    FavoriteModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbg.generated Wed Feb 22 13:04:31 CST 2023
     */
    int updateByPrimaryKeySelective(FavoriteModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbg.generated Wed Feb 22 13:04:31 CST 2023
     */
    int updateByPrimaryKey(FavoriteModel record);
    List<FavoriteModel> selectAll(Integer userID);
}