package com.imooc.policy.dal;

import com.imooc.policy.model.SellerModel;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface SellerModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Fri Jul 19 12:00:18 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Fri Jul 19 12:00:18 CST 2019
     */
    int insert(SellerModel record);

    List<SellerModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Fri Jul 19 12:00:18 CST 2019
     */
    int insertSelective(SellerModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Fri Jul 19 12:00:18 CST 2019
     */
    SellerModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Fri Jul 19 12:00:18 CST 2019
     */
    int updateByPrimaryKeySelective(SellerModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Fri Jul 19 12:00:18 CST 2019
     */
    int updateByPrimaryKey(SellerModel record);
    Integer countAllSeller();
}