package com.imooc.dianping.dal;

import com.imooc.dianping.model.ClickModel;

public interface ClickModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table click
     *
     * @mbg.generated Tue Feb 14 10:37:37 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table click
     *
     * @mbg.generated Tue Feb 14 10:37:37 CST 2023
     */
    int insert(ClickModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table click
     *
     * @mbg.generated Tue Feb 14 10:37:37 CST 2023
     */
    int insertSelective(ClickModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table click
     *
     * @mbg.generated Tue Feb 14 10:37:37 CST 2023
     */
    ClickModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table click
     *
     * @mbg.generated Tue Feb 14 10:37:37 CST 2023
     */
    int updateByPrimaryKeySelective(ClickModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table click
     *
     * @mbg.generated Tue Feb 14 10:37:37 CST 2023
     */
    int updateByPrimaryKey(ClickModel record);
}