package com.imooc.dianping.dal;

import com.imooc.dianping.model.SortModel;

public interface SortModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbg.generated Mon Feb 13 23:41:43 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbg.generated Mon Feb 13 23:41:43 CST 2023
     */
    int insert(SortModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbg.generated Mon Feb 13 23:41:43 CST 2023
     */
    int insertSelective(SortModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbg.generated Mon Feb 13 23:41:43 CST 2023
     */
    SortModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbg.generated Mon Feb 13 23:41:43 CST 2023
     */
    int updateByPrimaryKeySelective(SortModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbg.generated Mon Feb 13 23:41:43 CST 2023
     */
    int updateByPrimaryKey(SortModel record);
}