package com.imooc.dianping.model;

public class ClickModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column click.id
     *
     * @mbg.generated Tue Feb 14 10:37:37 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column click.user_id
     *
     * @mbg.generated Tue Feb 14 10:37:37 CST 2023
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column click.policy_grade
     *
     * @mbg.generated Tue Feb 14 10:37:37 CST 2023
     */
    private Integer policyGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column click.policy_title
     *
     * @mbg.generated Tue Feb 14 10:37:37 CST 2023
     */
    private Integer policyTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column click.policy_body
     *
     * @mbg.generated Tue Feb 14 10:37:37 CST 2023
     */
    private Integer policyBody;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column click.pub_time
     *
     * @mbg.generated Tue Feb 14 10:37:37 CST 2023
     */
    private Integer pubTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column click.id
     *
     * @return the value of click.id
     *
     * @mbg.generated Tue Feb 14 10:37:37 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column click.id
     *
     * @param id the value for click.id
     *
     * @mbg.generated Tue Feb 14 10:37:37 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column click.user_id
     *
     * @return the value of click.user_id
     *
     * @mbg.generated Tue Feb 14 10:37:37 CST 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column click.user_id
     *
     * @param userId the value for click.user_id
     *
     * @mbg.generated Tue Feb 14 10:37:37 CST 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column click.policy_grade
     *
     * @return the value of click.policy_grade
     *
     * @mbg.generated Tue Feb 14 10:37:37 CST 2023
     */
    public Integer getPolicyGrade() {
        return policyGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column click.policy_grade
     *
     * @param policyGrade the value for click.policy_grade
     *
     * @mbg.generated Tue Feb 14 10:37:37 CST 2023
     */
    public void setPolicyGrade(Integer policyGrade) {
        this.policyGrade = policyGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column click.policy_title
     *
     * @return the value of click.policy_title
     *
     * @mbg.generated Tue Feb 14 10:37:37 CST 2023
     */
    public Integer getPolicyTitle() {
        return policyTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column click.policy_title
     *
     * @param policyTitle the value for click.policy_title
     *
     * @mbg.generated Tue Feb 14 10:37:37 CST 2023
     */
    public void setPolicyTitle(Integer policyTitle) {
        this.policyTitle = policyTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column click.policy_body
     *
     * @return the value of click.policy_body
     *
     * @mbg.generated Tue Feb 14 10:37:37 CST 2023
     */
    public Integer getPolicyBody() {
        return policyBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column click.policy_body
     *
     * @param policyBody the value for click.policy_body
     *
     * @mbg.generated Tue Feb 14 10:37:37 CST 2023
     */
    public void setPolicyBody(Integer policyBody) {
        this.policyBody = policyBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column click.pub_time
     *
     * @return the value of click.pub_time
     *
     * @mbg.generated Tue Feb 14 10:37:37 CST 2023
     */
    public Integer getPubTime() {
        return pubTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column click.pub_time
     *
     * @param pubTime the value for click.pub_time
     *
     * @mbg.generated Tue Feb 14 10:37:37 CST 2023
     */
    public void setPubTime(Integer pubTime) {
        this.pubTime = pubTime;
    }
}