package com.imooc.dianping.model;

import java.util.Date;

public class FavoriteModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.id
     *
     * @mbg.generated Wed Feb 22 13:06:14 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.user_id
     *
     * @mbg.generated Wed Feb 22 13:06:14 CST 2023
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.policy_id
     *
     * @mbg.generated Wed Feb 22 13:06:14 CST 2023
     */
    private Integer policyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.create_time
     *
     * @mbg.generated Wed Feb 22 13:06:14 CST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.update_time
     *
     * @mbg.generated Wed Feb 22 13:06:14 CST 2023
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.status
     *
     * @mbg.generated Wed Feb 22 13:06:14 CST 2023
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.id
     *
     * @return the value of favorite.id
     *
     * @mbg.generated Wed Feb 22 13:06:14 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.id
     *
     * @param id the value for favorite.id
     *
     * @mbg.generated Wed Feb 22 13:06:14 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.user_id
     *
     * @return the value of favorite.user_id
     *
     * @mbg.generated Wed Feb 22 13:06:14 CST 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.user_id
     *
     * @param userId the value for favorite.user_id
     *
     * @mbg.generated Wed Feb 22 13:06:14 CST 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.policy_id
     *
     * @return the value of favorite.policy_id
     *
     * @mbg.generated Wed Feb 22 13:06:14 CST 2023
     */
    public Integer getPolicyId() {
        return policyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.policy_id
     *
     * @param policyId the value for favorite.policy_id
     *
     * @mbg.generated Wed Feb 22 13:06:14 CST 2023
     */
    public void setPolicyId(Integer policyId) {
        this.policyId = policyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.create_time
     *
     * @return the value of favorite.create_time
     *
     * @mbg.generated Wed Feb 22 13:06:14 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.create_time
     *
     * @param createTime the value for favorite.create_time
     *
     * @mbg.generated Wed Feb 22 13:06:14 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.update_time
     *
     * @return the value of favorite.update_time
     *
     * @mbg.generated Wed Feb 22 13:06:14 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.update_time
     *
     * @param updateTime the value for favorite.update_time
     *
     * @mbg.generated Wed Feb 22 13:06:14 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.status
     *
     * @return the value of favorite.status
     *
     * @mbg.generated Wed Feb 22 13:06:14 CST 2023
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.status
     *
     * @param status the value for favorite.status
     *
     * @mbg.generated Wed Feb 22 13:06:14 CST 2023
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}