package com.imooc.dianping.model;

public class SortModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort.id
     *
     * @mbg.generated Mon Feb 13 23:41:43 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort.policy_title
     *
     * @mbg.generated Mon Feb 13 23:41:43 CST 2023
     */
    private Double policyTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort.policy_body
     *
     * @mbg.generated Mon Feb 13 23:41:43 CST 2023
     */
    private Double policyBody;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort.policy_grade
     *
     * @mbg.generated Mon Feb 13 23:41:43 CST 2023
     */
    private Double policyGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort.pub_time
     *
     * @mbg.generated Mon Feb 13 23:41:43 CST 2023
     */
    private Double pubTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort.policy_zone
     *
     * @mbg.generated Mon Feb 13 23:41:43 CST 2023
     */
    private Double policyZone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort.user_id
     *
     * @mbg.generated Mon Feb 13 23:41:43 CST 2023
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort.id
     *
     * @return the value of sort.id
     *
     * @mbg.generated Mon Feb 13 23:41:43 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort.id
     *
     * @param id the value for sort.id
     *
     * @mbg.generated Mon Feb 13 23:41:43 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort.policy_title
     *
     * @return the value of sort.policy_title
     *
     * @mbg.generated Mon Feb 13 23:41:43 CST 2023
     */
    public Double getPolicyTitle() {
        return policyTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort.policy_title
     *
     * @param policyTitle the value for sort.policy_title
     *
     * @mbg.generated Mon Feb 13 23:41:43 CST 2023
     */
    public void setPolicyTitle(Double policyTitle) {
        this.policyTitle = policyTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort.policy_body
     *
     * @return the value of sort.policy_body
     *
     * @mbg.generated Mon Feb 13 23:41:43 CST 2023
     */
    public Double getPolicyBody() {
        return policyBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort.policy_body
     *
     * @param policyBody the value for sort.policy_body
     *
     * @mbg.generated Mon Feb 13 23:41:43 CST 2023
     */
    public void setPolicyBody(Double policyBody) {
        this.policyBody = policyBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort.policy_grade
     *
     * @return the value of sort.policy_grade
     *
     * @mbg.generated Mon Feb 13 23:41:43 CST 2023
     */
    public Double getPolicyGrade() {
        return policyGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort.policy_grade
     *
     * @param policyGrade the value for sort.policy_grade
     *
     * @mbg.generated Mon Feb 13 23:41:43 CST 2023
     */
    public void setPolicyGrade(Double policyGrade) {
        this.policyGrade = policyGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort.pub_time
     *
     * @return the value of sort.pub_time
     *
     * @mbg.generated Mon Feb 13 23:41:43 CST 2023
     */
    public Double getPubTime() {
        return pubTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort.pub_time
     *
     * @param pubTime the value for sort.pub_time
     *
     * @mbg.generated Mon Feb 13 23:41:43 CST 2023
     */
    public void setPubTime(Double pubTime) {
        this.pubTime = pubTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort.policy_zone
     *
     * @return the value of sort.policy_zone
     *
     * @mbg.generated Mon Feb 13 23:41:43 CST 2023
     */
    public Double getPolicyZone() {
        return policyZone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort.policy_zone
     *
     * @param policyZone the value for sort.policy_zone
     *
     * @mbg.generated Mon Feb 13 23:41:43 CST 2023
     */
    public void setPolicyZone(Double policyZone) {
        this.policyZone = policyZone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort.user_id
     *
     * @return the value of sort.user_id
     *
     * @mbg.generated Mon Feb 13 23:41:43 CST 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort.user_id
     *
     * @param userId the value for sort.user_id
     *
     * @mbg.generated Mon Feb 13 23:41:43 CST 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}