package com.imooc.policy.model;

public class BehaviorModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behavior.id
     *
     * @mbg.generated Tue Feb 14 10:38:00 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behavior.user_id
     *
     * @mbg.generated Tue Feb 14 10:38:00 CST 2023
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behavior.policy_id
     *
     * @mbg.generated Tue Feb 14 10:38:00 CST 2023
     */
    private Integer policyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behavior.click_num
     *
     * @mbg.generated Tue Feb 14 10:38:00 CST 2023
     */
    private Integer clickNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behavior.id
     *
     * @return the value of behavior.id
     *
     * @mbg.generated Tue Feb 14 10:38:00 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behavior.id
     *
     * @param id the value for behavior.id
     *
     * @mbg.generated Tue Feb 14 10:38:00 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behavior.user_id
     *
     * @return the value of behavior.user_id
     *
     * @mbg.generated Tue Feb 14 10:38:00 CST 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behavior.user_id
     *
     * @param userId the value for behavior.user_id
     *
     * @mbg.generated Tue Feb 14 10:38:00 CST 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behavior.policy_id
     *
     * @return the value of behavior.policy_id
     *
     * @mbg.generated Tue Feb 14 10:38:00 CST 2023
     */
    public Integer getPolicyId() {
        return policyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behavior.policy_id
     *
     * @param policyId the value for behavior.policy_id
     *
     * @mbg.generated Tue Feb 14 10:38:00 CST 2023
     */
    public void setPolicyId(Integer policyId) {
        this.policyId = policyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behavior.click_num
     *
     * @return the value of behavior.click_num
     *
     * @mbg.generated Tue Feb 14 10:38:00 CST 2023
     */
    public Integer getClickNum() {
        return clickNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behavior.click_num
     *
     * @param clickNum the value for behavior.click_num
     *
     * @mbg.generated Tue Feb 14 10:38:00 CST 2023
     */
    public void setClickNum(Integer clickNum) {
        this.clickNum = clickNum;
    }
}