package com.imooc.policy.model;

public class ClickModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column click.id
     *
     * @mbg.generated Fri Feb 24 14:37:03 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column click.user_id
     *
     * @mbg.generated Fri Feb 24 14:37:03 CST 2023
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column click.click_chose
     *
     * @mbg.generated Fri Feb 24 14:37:03 CST 2023
     */
    private Integer clickChose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column click.rating
     *
     * @mbg.generated Fri Feb 24 14:37:03 CST 2023
     */
    private Integer rating;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column click.id
     *
     * @return the value of click.id
     *
     * @mbg.generated Fri Feb 24 14:37:03 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column click.id
     *
     * @param id the value for click.id
     *
     * @mbg.generated Fri Feb 24 14:37:03 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column click.user_id
     *
     * @return the value of click.user_id
     *
     * @mbg.generated Fri Feb 24 14:37:03 CST 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column click.user_id
     *
     * @param userId the value for click.user_id
     *
     * @mbg.generated Fri Feb 24 14:37:03 CST 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column click.click_chose
     *
     * @return the value of click.click_chose
     *
     * @mbg.generated Fri Feb 24 14:37:03 CST 2023
     */
    public Integer getClickChose() {
        return clickChose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column click.click_chose
     *
     * @param clickChose the value for click.click_chose
     *
     * @mbg.generated Fri Feb 24 14:37:03 CST 2023
     */
    public void setClickChose(Integer clickChose) {
        this.clickChose = clickChose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column click.rating
     *
     * @return the value of click.rating
     *
     * @mbg.generated Fri Feb 24 14:37:03 CST 2023
     */
    public Integer getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column click.rating
     *
     * @param rating the value for click.rating
     *
     * @mbg.generated Fri Feb 24 14:37:03 CST 2023
     */
    public void setRating(Integer rating) {
        this.rating = rating;
    }
}