package com.imooc.policy.model;

public class PolicyModelWithBLOBs extends PolicyModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy.pub_agency_id
     *
     * @mbg.generated Fri Feb 10 11:10:59 CST 2023
     */
    private String pubAgencyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy.POLICY_BODY
     *
     * @mbg.generated Fri Feb 10 11:10:59 CST 2023
     */
    private String policyBody;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy.pub_agency_id
     *
     * @return the value of policy.pub_agency_id
     *
     * @mbg.generated Fri Feb 10 11:10:59 CST 2023
     */
    public String getPubAgencyId() {
        return pubAgencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy.pub_agency_id
     *
     * @param pubAgencyId the value for policy.pub_agency_id
     *
     * @mbg.generated Fri Feb 10 11:10:59 CST 2023
     */
    public void setPubAgencyId(String pubAgencyId) {
        this.pubAgencyId = pubAgencyId == null ? null : pubAgencyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy.POLICY_BODY
     *
     * @return the value of policy.POLICY_BODY
     *
     * @mbg.generated Fri Feb 10 11:10:59 CST 2023
     */
    public String getPolicyBody() {
        return policyBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy.POLICY_BODY
     *
     * @param policyBody the value for policy.POLICY_BODY
     *
     * @mbg.generated Fri Feb 10 11:10:59 CST 2023
     */
    public void setPolicyBody(String policyBody) {
        this.policyBody = policyBody == null ? null : policyBody.trim();
    }
}